language: cpp

compiler:
  - gcc
  
before_install:
  # this doesn't work - sudo add-apt-repository -y ppa:timsc/opencv-3.3
  - sudo apt-get update

install:

  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make hello.bin
   
  
  

after_success:
deploy:
  provider: releases
  api_key: "0f74fbe14901e8106746c1b5a3032fea7cc7a607"
  file_glob: true
  file: *.bin
  skip_cleanup: true
  draft: true
