language: cpp

compiler:
  - gcc
  
before_install:
  # this doesn't work - sudo add-apt-repository -y ppa:timsc/opencv-3.3
  - sudo apt-get update

install:

  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make hello.bin
   

after_success:
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file_glob: true
  file: h*.bin
  skip_cleanup: true
  draft: true
  edge: true
  
