language: cpp

compiler:
  - gcc
  
before_install:
  # this doesn't work - sudo add-apt-repository -y ppa:timsc/opencv-3.3
  - sudo apt-get update

install:

  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make hello.bin
   
  
  

after_success:
deploy:
  provider: releases
  api_key: "0dffe249e564254e1164bad990265812b7ae6d2d"
  file_glob: true
  file: h*.bin
  skip_cleanup: true
  draft: true
